export const SET_STATE = 'search/SET_STATE';
export const SEARCH_GET_OFFER_LIST = 'SEARCH_GET_OFFER_LIST';
export const SEARCH_SET_OFFER_LIST = 'SEARCH_SET_OFFER_LIST';
export const SEARCH_SET_CACHE_LIST = 'SEARCH_SET_CACHE_LIST';
export const SEARCH_LOG = 'SEARCH_LOG';
export const SEARCH_SET_RESULT = 'SEARCH_SET_RESULT';
