export const SET_STATE = 'shippingList/SET_STATE';
export const SHIPPING_GET_SHIPPING_LIST = 'GET_SHIPPING_LIST';
export const SHIPPING_GET_SHIPPING_LIST_GROUP = 'GET_SHIPPING_LIST_GROUP';
export const SHIPPING_GET_SHIPPING_DETAIL = 'GET_SHIPPING_DETAIL';
export const SHIPPING_GET_GROUP_SHIPPING_DETAIL = 'GET_GROUP_SHIPPING_DETAIL';
export const CHANGE_STATUS_DELIVERED = 'CHANGE_STATUS_DELIVERED';
export const GET_USER_BANK_DETAILS = 'GET_USER_BANK_DETAILS';
export const ADD_USER_BANK_DETAILS = 'ADD_USER_BANK_DETAILS';
export const SHIPPING_RETURN = 'SHIPPING_RETURN';
export const GET_CL_EARNING = 'GET_CL_EARNING';
export const VERIFY_USER_BANK_DETAILS = 'VERIFY_USER_BANK_DETAILS';
export const CHECK_ACCOUNT_VERIFICATION_STATUS =
  'CHECK_ACCOUNT_VERIFICATION_STATUS';
